controllers/UsersPageController.php
<?php

namespace app\controllers;

use Yii;
use app\models\UsersPage;
use app\models\UsersPageSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;
use app\models\blocks\TextBlock;
use app\models\PageBlocks;
use app\models\blocks\LinkBlock;
use app\models\blocks\SeparatorBlock;
use app\models\blocks\HtmlBlock;
use app\models\blocks\AvatarBlock;
use app\models\blocks\SocialBlock;
use app\models\blocks\VideoBlock;
use app\models\blocks\MessengerBlock;
use app\models\blocks\QuestionBlock;
use app\models\blocks\UniqueSellingBlock;
use app\models\blocks\CaruselBlock;
use app\models\blocks\AdvantageBlock;
use app\models\blocks\MapBlock;
use app\models\blocks\ContactFormBlock;
use app\models\blocks\ProductBlock;
use app\models\additional\Clicks;
use app\models\additional\HistoryPages;
use yii\web\UploadedFile;

use app\models\blocks\MapMarks;
use katzz0\yandexmaps\Map;
use katzz0\yandexmaps\JavaScript;
use katzz0\yandexmaps\objects\Placemark;
use katzz0\yandexmaps\Polyline;
use katzz0\yandexmaps\Point;
use katzz0\yandexmaps\Canvas as YandexMaps;

/**
 * UsersPageController implements the CRUD actions for UsersPage model.
 */
class UsersPageController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                   [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all UsersPage models.
     * @return mixed
     */
    public function actionIndex()
    {    
        $searchModel = new UsersPageSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Users Page model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($user_id)
    {
        $pages = UsersPage::find()->where(['user_id' => $user_id])->andWhere(['!=', 'is_main', 1 ])->all();
        $actual = UsersPage::find()->where(['user_id' => $user_id, 'is_main' => 1])->one();
        $request = Yii::$app->request;
        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                    'title'=> "Страницы",
                    'content'=>$this->renderAjax('view', [
                        'pages' => $pages,
                        'user_id' => $user_id,
                        'actual' => $actual,
                    ]),
                ];    
        }else{
            return $this->render('view', [
                'pages' => $pages,
                'user_id' => $user_id,
                'actual' => $actual,
            ]);
        }
    }

    /**
     * Updates an existing Users Page model.
     * For ajax request will return json object
     * and for non-ajax request if update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);       

        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($model->load($request->post()) && $model->save()){
                return [
                    'forceReload'=>'#page-pjax',
                    'forceClose'=>true,
                ];    
            }else{
                 return [
                    'title'=> "Изменить",
                    'content'=>$this->renderAjax('_update_form', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])
                ];        
            }
        }
    }

    //Вкладка "Страница"
    public function actionPage($user_id = null, $id = null)
    {    
        $request = Yii::$app->request;
        if($request->post()) {
            $post = $request->post();
            $active = $post['active'];
            $strlen = strlen( $active );
            $page_block_id = ''; $order_number = 0;
            for( $i = 0; $i <= $strlen; $i++ ) {
                $char = substr( $active, $i, 1 );             
                if($char == ',') {
                    $order_number++;
                    Yii::$app->db->createCommand()->update('page_blocks', 
                        [ 'sorting' => $order_number ], 
                        [ 'id' => $page_block_id ])
                    ->execute();
                    $page_block_id = '';
                }
                else $page_block_id .= $char;
            }
            $order_number++;
            Yii::$app->db->createCommand()->update('page_blocks', 
                [ 'sorting' => $order_number ], 
                [ 'id' => $page_block_id ])
            ->execute();
            Yii::$app->session->setFlash('success', "Успешно выполнено");
        }

        if($user_id != null) {
            $model = UsersPage::find()->where(['user_id' => $user_id, 'active' => 1])->one();
        }
        if($id != null) {
            $model = UsersPage::findOne($id);
        }

        $active = [];
        if($model != null) {
            $i=0;
            $blocks = PageBlocks::find()->where(['page_id' => $model->id])->orderBy([ 'sorting' => SORT_ASC])->all();
            foreach ($blocks as $block) {
                $i++;
                if( $block->table_name == 'text_block') {
                    $textBlock = TextBlock::findOne($block->field_id);
                    $name = $textBlock->getItemValues();
                    $active += [
                        $block->id => ['content' => $name],
                    ];
                }
                if( $block->table_name == 'link_block') {
                    $linkBlock = LinkBlock::findOne($block->field_id);
                    $name = $linkBlock->getItemValues();
                    $active += [
                        $block->id => ['content' => $name],
                    ];
                }
                if( $block->table_name == 'separator_block') {
                    $separatorBlock = SeparatorBlock::findOne($block->field_id);
                    $name = $separatorBlock->getItemValues();
                    $active += [
                        $block->id => ['content' => $name],
                    ];
                }
                if( $block->table_name == 'html_block') {
                    $htmlBlock = HtmlBlock::findOne($block->field_id);
                    $name = $htmlBlock->getItemValues();
                    $active += [
                        $block->id => ['content' => $name],
                    ];
                }

                if( $block->table_name == 'avatar_block') {
                    $avatarBlock = AvatarBlock::findOne($block->field_id);
                    $name = $avatarBlock->getItemValues();
                    $active += [
                        $block->id => ['content' => $name],
                    ];
                }

                if( $block->table_name == 'social_block') {
                    $socialBlock = SocialBlock::findOne($block->field_id);
                    $name = $socialBlock->getItemValues($this->actionGetSocial($block->field_id));
                    $active += [
                        $block->id => ['content' => $name],
                    ];
                }

                if( $block->table_name == 'video_block') {
                    $videoBlock = VideoBlock::findOne($block->field_id);
                    $name = $videoBlock->getItemValues($this->actionGetVideo($block->field_id));
                    $active += [
                        $block->id => ['content' => $name],
                    ];
                }

                if( $block->table_name == 'messenger_block') {
                    $messengerBlock = MessengerBlock::findOne($block->field_id);
                    $name = $messengerBlock->getItemValues($this->actionGetMessenger($block->field_id));
                    $active += [
                        $block->id => ['content' => $name],
                    ];
                }

                if( $block->table_name == 'question_block') {
                    $questionBlock = QuestionBlock::find()->where(['number' => $block->field_id])->one();
                    $name = $questionBlock->getItemValues($this->actionGetQuestions($block->field_id));
                    $active += [
                        $block->id => ['content' => $name],
                    ];
                }

                if( $block->table_name == 'carusel_block') {
                    $caruselBlock = CaruselBlock::find()->where(['number' => $block->field_id])->one();
                    $name = $caruselBlock->getItemValues($this->actionGetCarusel($block->field_id));
                    $active += [
                        $block->id => ['content' => $name],
                    ];
                }

                if( $block->table_name == 'advantage_block') {
                    $advantageBlock = AdvantageBlock::find()->where(['number' => $block->field_id])->one();
                    $name = $advantageBlock->getItemValues($this->actionGetAdvantage($block->field_id));
                    $active += [

views/users-page/_add_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\UsersPage */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="users-page-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'link_name')->textInput(['maxlength' => true]) ?>

	<div style="display: none;">
	    <?= $form->field($model, 'user_id')->textInput() ?>	
	</div>
  
	<?php if (!Yii::$app->request->isAjax){ ?>
	  	<div class="form-group">
	        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
	    </div>
	<?php } ?>

    <?php ActiveForm::end(); ?>
    
</div>

views/users-page/_add_page.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\UsersPage */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="users-page-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'page_number')->dropDownList($model->getPageList(Yii::$app->user->identity->id), ['prompt' => 'Выберите' ]) ?>
  
	<?php if (!Yii::$app->request->isAjax){ ?>
	  	<div class="form-group">
	        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
	    </div>
	<?php } ?>

    <?php ActiveForm::end(); ?>
    
</div>

views/users-page/_columns.php
<?php
use yii\helpers\Url;

return [
    [
        'class' => 'kartik\grid\CheckboxColumn',
        'width' => '20px',
    ],
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'user_id',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'name',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'link_name',
    ],
    [
        'class' => 'kartik\grid\ActionColumn',
        'dropdown' => false,
        'vAlign'=>'middle',
        'urlCreator' => function($action, $model, $key, $index) { 
                return Url::to([$action,'id'=>$key]);
        },
        'viewOptions'=>['role'=>'modal-remote','title'=>'View','data-toggle'=>'tooltip'],
        'updateOptions'=>['role'=>'modal-remote','title'=>'Update', 'data-toggle'=>'tooltip'],
        'deleteOptions'=>['role'=>'modal-remote','title'=>'Delete', 
                          'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                          'data-request-method'=>'post',
                          'data-toggle'=>'tooltip',
                          'data-confirm-title'=>'Are you sure?',
                          'data-confirm-message'=>'Are you sure want to delete this item'], 
    ],

];   

views/users-page/_template_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

if (!file_exists('images/templates/'.$model->image) || $model->image == null) {
    $path = 'http://' . $_SERVER['SERVER_NAME'].'/images/no-images.jpg';
} else {
    $path = 'http://' . $_SERVER['SERVER_NAME'].'/images/templates/'.$model->image;
}

?>

<div class="users-page-form">

    <?php $form = ActiveForm::begin([ 'options' => ['method' => 'post', 'enctype' => 'multipart/form-data']]); ?>
	
		<div style="padding:20px;">
			<div class="row">			
			    <div class="col-md-12">
			        <center>
			        <?=Html::img($path, [
			            'style' => 'width:350px; height:250px;',
			            //'class' => 'img-circle',
			        ])?>
			        </center>
			    </div>

				<div class="col-md-6">
			    	<?= $form->field($model, 'name')->textInput(['maxlength' => true, 'placeholder' => 'Шаблоны страниц' ]) ?>
			    </div>

				<div class="col-md-6">
				    <?= $form->field($model, 'link_name')->textInput(['maxlength' => true, ]) ?>
				</div>

				<div class="col-md-12">
			    	<?= $form->field($model, 'description')->textArea(['rows' => 3]) ?>
			    </div>

				<div class="col-md-12">
			    	<?= $form->field($model, 'file')->fileInput(); ?>
				</div>
			  
				<?php if (!Yii::$app->request->isAjax){ ?>
				  	<div class="form-group">
				        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
				    </div>
				<?php } ?>
			</div>
		</div>

    <?php ActiveForm::end(); ?>
    
</div>

views/users-page/_update_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\UsersPage */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="users-page-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

  
	<?php if (!Yii::$app->request->isAjax){ ?>
	  	<div class="form-group">
	        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
	    </div>
	<?php } ?>

    <?php ActiveForm::end(); ?>
    
</div>

views/users-page/add.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\UsersPage */

?>
<div class="users-page-create">
    <?= $this->render('_add_form', [
        'model' => $model,
    ]) ?>
</div>

views/users-page/change_form.php
<?php
use kartik\sortinput\SortableInput;
use yii\widgets\ActiveForm;
use yii\helpers\Html;

?>
<div class="users-page-index">
    <div id="ajaxCrudDatatable">
		<?php $form = ActiveForm::begin(['id' => 'date-form']); ?>
			<div class="row">
				<div class="col-md-8" style="margin-left: 15%;">
					<?= SortableInput::widget([
					    'name'=>'active',
					    'items' => $active, 
					    'hideInput' => true,
					    'sortableOptions' => [
					        'connected'=>true,
					        'itemOptions'=>['class'=>'alert alert-success'],
					    ],
					    'options' => ['class'=>'form-control', 'readonly'=>true]
					])?>
				</div>
			</div>
		<?php ActiveForm::end(); ?>
    </div>
</div>

views/users-page/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\UsersPage */

?>
<div class="users-page-create">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

views/users-page/index.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use kartik\grid\GridView;
use johnitvn\ajaxcrud\CrudAsset; 
use johnitvn\ajaxcrud\BulkButtonWidget;

/* @var $this yii\web\View */
/* @var $searchModel app\models\UsersPageSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Users Pages';
$this->params['breadcrumbs'][] = $this->title;

CrudAsset::register($this);

?>
<div class="users-page-index">
    <div id="ajaxCrudDatatable">
        <?=GridView::widget([
            'id'=>'crud-datatable',
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'pjax'=>true,
            'columns' => require(__DIR__.'/_columns.php'),
            'toolbar'=> [
                ['content'=>
                    Html::a('<i class="glyphicon glyphicon-plus"></i>', ['create'],
                    ['role'=>'modal-remote','title'=> 'Create new Users Pages','class'=>'btn btn-default']).
                    Html::a('<i class="glyphicon glyphicon-repeat"></i>', [''],
                    ['data-pjax'=>1, 'class'=>'btn btn-default', 'title'=>'Reset Grid']).
                    '{toggleData}'.
                    '{export}'
                ],
            ],          
            'striped' => true,
            'condensed' => true,
            'responsive' => true,          
            'panel' => [
                'type' => 'primary', 
                'heading' => '<i class="glyphicon glyphicon-list"></i> Users Pages listing',
                'before'=>'<em>* Resize table columns just like a spreadsheet by dragging the column edges.</em>',
                'after'=>BulkButtonWidget::widget([
                            'buttons'=>Html::a('<i class="glyphicon glyphicon-trash"></i>&nbsp; Delete All',
                                ["bulk-delete"] ,
                                [
                                    "class"=>"btn btn-danger btn-xs",
                                    'role'=>'modal-remote-bulk',
                                    'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                                    'data-request-method'=>'post',
                                    'data-confirm-title'=>'Are you sure?',
                                    'data-confirm-message'=>'Are you sure want to delete this item'
                                ]),
                        ]).                        
                        '<div class="clearfix"></div>',
            ]
        ])?>
    </div>
</div>
<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    "footer"=>"",// always need it for jquery plugin
])?>
<?php Modal::end(); ?>

views/users-page/templates.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use johnitvn\ajaxcrud\CrudAsset;
use yii\widgets\Pjax;
use yii\bootstrap\Modal;

CrudAsset::register($this);
?>


<?php Pjax::begin(['enablePushState' => false, 'id' => 'template-pjax']) ?>
<div class="templates">

	<?php if(Yii::$app->user->identity->type == 0){ ?>
		<center>
			<?= Html::a('Создать новый шаблон страниц', ['add-template'], ['role'=>'modal-remote','title'=> 'Создать','class'=>'btn btn-primary']) ?>
		</center>
	<?php } ?>

	<div class="row" style="margin-top: 50px;">
		<?php
			foreach ($templates as $template) {

				$update = '';
				if(Yii::$app->user->identity->type == 0) $update = '<a data-pjax="0" href="'.Url::toRoute(['/users-page/page', 'id' => $template->id]).'"><i class="glyphicon glyphicon-pencil" ></i></a> <a role="modal-remote" href="'.Url::toRoute(['/users-page/add-template', 'id' => $template->id]).'"><i class="glyphicon glyphicon-eye-open" ></i></a> ';

				if (!file_exists('images/templates/'.$template->image) || $template->image == null) {
				    $path = 'http://' . $_SERVER['SERVER_NAME'].'/images/no-images.jpg';
				} else {
				    $path = 'http://' . $_SERVER['SERVER_NAME'].'/images/templates/'.$template->image;
				}

		?>
			<div class="col-md-6 col-xs-12 col-sm-6 has-mb-4">
				<div class="panel panel-success">
					<div class="panel-heading">
						<h3 class="panel-title"><?=$update . $template->name?></h3>
						<span class="btn-group pull-right">
				            <button type="button" class="btn btn-warning btn-xs arxiv">Добавить к себе как ...</button>
				            <button type="button" class="btn btn-warning btn-xs dropdown-toggle dropdown1" data-toggle="dropdown" aria-expanded="false">
				                <span style="margin-top: 1px;" class="caret"></span>
				            </button>
				            <ul class="dropdown-menu" role="menu">
				                <li><?= Html::a('Профайл', ['/users-page/import-template', 'type' => 'profile', 'template_id' => $template->id], ['role'=>'modal-remote','class'=>'top','style'=>'width :200px;text-align: left;'])?></li>
				                <li><?= Html::a('Главной страницы', ['/users-page/import-template', 'type' => 'main', 'template_id' => $template->id], ['role'=>'modal-remote','class'=>'top','style'=>'width :200px;text-align: left;'])?></li>
				            </ul>
				        </span>
					</div>
					<div class="panel-body">
						<div class="table-responsive">
							<center>
						        <?=Html::img($path, [
						            'style' => 'width:350px; height:250px;',
						            //'class' => 'img-circle',
						        ])?>
							</center>
							<br>
				            <table class="table table-bordered">    
				                <tr>
				                    <td style="font-weight: bold; font-size: 16px;">Ссылка</td>
				                    <td>
				                    	<?= Html::a('<span class="is-hidden-mobile">http://'. $_SERVER['SERVER_NAME'].'/'.$template->link_name .'	</span>', ['/'.$template->link_name], ['data-pjax' => '0', 'target'=> "_blank"]) ?>
				                    </td>
				                </tr>				               
				                <tr>
				                    <td style="font-weight: bold; font-size: 16px;">Описание</td>
				                   	<td><?=$template->description?></td>
				                </tr>				                
				            </table>
				        </div>
					</div>
				</div>
			</div>
		<?php
			}
		?>
	</div>    
</div>
<?php Pjax::end() ?>

<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    "options" => [
        "tabindex" => false,
    ],
    "footer"=>"",// always need it for jquery plugin
])?>
<?php Modal::end(); ?>

views/users-page/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\UsersPage */
?>
<div class="users-page-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/users-page/view.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\UsersPage */
?>
<div class="users-page-view">
 
	<div style="padding: 1px;">
		<?= Html::a('Главная страница', ['set-main', 'user_id' => $user_id, 'page_id' => $actual->id,], ['role'=>'modal-remote','title'=> 'Сделать страницу как активное','class'=>'btn ', 'style' => 'width:100%; background-color: #d9edf7; ']) ?>
	</div>
	<div style="padding: 1px;">
		<?= Html::a('<i class="fa fa-plus"></i> Создать новую страницу', ['add', 'user_id' => $user_id, 'active' => 0, 'is_main' => 0 ], ['role'=>'modal-remote','title'=> 'Создать новую страницу','class'=>'btn ', 'style' => 'width:100%; background-color: #d9edf7; ']) ?>
	</div>
	<div style="margin-top: 5px;">
		<?php 
			foreach ($pages as $page) {
		?>
		<div style="padding: 1px;">
			<?= 
				Html::a($page->name, ['set-main', 'user_id' => $user_id, 'page_id' => $page->id,], ['role'=>'modal-remote','title'=> 'Создать','class'=>'btn ', 'style' => 'width:92%; background-color: #d9edf7; ']) . ' ' . 
				Html::a('<i class="glyphicon glyphicon-pencil"></i>', ['/users-page/update', 'id' => $page->id], ['role'=>'modal-remote','title'=> 'Изменить страницу',]) . ' ' . 
				Html::a('<span class="glyphicon glyphicon-trash"></span>', [ '/users-page/delete', 'id' => $page->id ], 
				[
					'role'=>'modal-remote','title'=>'Удалить', 
                    'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                    'data-request-method'=>'post',
                    'data-toggle'=>'tooltip',
                    'style' => 'cursor:pointer',
                    'data-confirm-title'=>'Подтвердите действие',
                    'data-confirm-message'=>'Вы действительно хотите удалить эту страницу?'                    
                ])
			?>
		</div>
		<?php
			}
		?> 
	</div>

</div>