controllers/ApplicationsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Applications;
use app\models\ApplicationsSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;
use app\models\additional\Contacts;
use app\models\additional\Columns;
use app\models\Template;

/**
 * ApplicationsController implements the CRUD actions for Applications model.
 */
class ApplicationsController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                   [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'bulk-delete' => ['post'],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        $tariff = Yii::$app->user->identity->tariff->key;
        if($tariff != 'pro') return $this->redirect(['/site/errors', 'type' => 1 ]);
        $this->enableCsrfValidation = true;
        return parent::beforeAction($action);        
    }

    /**
     * Lists all Applications models.
     * @return mixed
     */
    public function actionIndex()
    {    
        $request = Yii::$app->request;
        $post = $request->post();
        $searchModel = new ApplicationsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, Yii::$app->user->identity->id, $post);
        $contact = new Contacts();
        $contactProvider = $contact->searchContacts(Yii::$app->request->queryParams,Yii::$app->user->identity->id, $post);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'contactProvider' => $contactProvider,
            'contact' => $contact,
            'post' => $post,
        ]);
    }


    /**
     * Displays a single Applications model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {   
        $request = Yii::$app->request;
        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                    'title'=> "Заявка №". $id,
                    'size' => 'normal',
                    'content'=>$this->renderAjax('view', [
                        'model' => $this->findModel($id),
                    ]),
                ];    
        }else{
            return $this->render('view', [
                'model' => $this->findModel($id),
            ]);
        }
    }

    /**
     * Updates an existing Applications model.
     * For ajax request will return json object
     * and for non-ajax request if update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);       

        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            if($model->load($request->post()) && $model->save()){
                return [
                    'forceReload'=>'#crud-datatable-pjax',
                    'forceClose'=>true,
                ];    
            }else{
                 return [
                    'title'=> "Изменить",
                    'size' => 'large',
                    'content'=>$this->renderAjax('update', [
                        'model' => $model,
                    ]),
                    'footer'=> Html::button('Отмена',['class'=>'btn btn-default pull-left','data-dismiss'=>"modal"]).
                                Html::button('Сохранить',['class'=>'btn btn-primary','type'=>"submit"])
                ];        
            }
        }else{
            if ($model->load($request->post()) && $model->save()) {
                return $this->redirect(['view', 'id' => $model->id]);
            } else {
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
        }
    }

    //изменить статус заявок
    public function actionSetStatus($status,$id)
    {
        $model = $this->findModel($id);
        $model->status = $status;
        $model->save();
    }

    //изменение значения полю мин.оплаты на просмотре заявок
    public function actionSetPayType($status,$id)
    {
        $model = $this->findModel($id);
        $model->pay_type = $status;
        if($status != null) {
            $model->pay = 'payed';
            $model->status = 'ready';
            $model->pay_date = date('Y-m-d H:i:s');
        }else{
            $model->pay = 'not_payed';
            $model->status = 'working';
            $model->pay_date = null;
        }

        $model->save();
    }

    /**
     * Delete an existing Applications model.
     * For ajax request will return json object
     * and for non-ajax request if deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $request = Yii::$app->request;
        $this->findModel($id)->delete();

        if($request->isAjax){
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ['forceClose'=>true,'forceReload'=>'#crud-datatable-pjax'];
        }else{
            return $this->redirect(['index']);
        }
    }

    //Настроить колонки таблицы “Заявок”.
    public function actionSorting()
    {
        $request = Yii::$app->request;
        $user_id = Yii::$app->user->identity->id;       

        if ($request->post()) {
            $post = $request->post();
            $command = Yii::$app->db->createCommand();
            //aktiv columnlarni bazaga yozilishi
            $active = $post['active'];
            $strlen = strlen( $active );
            $id = ''; $order_number = 0;
            for( $i = 0; $i <= $strlen; $i++ ) {
                $char = substr( $active, $i, 1 );             
                if($char == ',') {
                    $order_number++;
                    $command->update('columns',['status'=>1,'order_number'=>$order_number],['id' => $id])->execute();
                    $id = '';
                }
                else $id .= $char;
            }

            $order_number++;
            $command->update('columns',['status'=>1,'order_number'=>$order_number],['id'=>$id])->execute();

            //aktiv bolmagan columnlarni bazaga yozilishi
            $noactive = $post['no-active'];
            $strlen = strlen( $noactive );
            $id = ''; 
            for( $i = 0; $i <= $strlen; $i++ ) {
                $char = substr( $noactive, $i, 1 );             
                if($char == ',') {
                    $command->update('columns', ['status' => 0 ], [ 'id' => $id ])->execute();
                    $id = '';
                }
                else $id .= $char;
            }
            $command->update('columns', ['status' => 0 ], [ 'id' => $id ])->execute();

            return $this->redirect(['/applications/index']);
        }else{
            $column = Columns::find()->where(['user_id'=>$user_id,'table_name'=>'applications'])->one();
            if($column == null ) {
                Applications::setDefaultValues($user_id);
            }

            $columns = Columns::find()
                ->where([
                    'user_id' => $user_id, 
                    'status' => 1, 
                    'table_name' => 'applications'
                ])
                ->orderBy([ 'order_number' => SORT_ASC ])
                ->all();
            $active = []; $i=0;
            foreach ($columns as $column) {
                $i++;
                $name = Template::getColumnsTemplate($i, $column->name);
                $active += [
                    $column->id => ['content' => $name],
                ];
            }

            $columns = Columns::find()->where(['user_id' => $user_id, 'status' => 0, 'table_name' => 'applications'])->all();
            $noactive = []; $i=0;
            foreach ($columns as $column) {
                $i++;
                $name = Template::getColumnsTemplate($i, $column->name);
                $noactive += [
                    $column->id => ['content' => $name],
                ];
            }
            
            return $this->render('sorting',[
                'active' => $active,
                'noactive' => $noactive,
            ]);
        }
    }


    /**
     * Finds the Applications model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Applications the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Applications::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/applications/_columns.php
<?php
use yii\helpers\Url;

return [
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'id',
        'content' => function($data){
            return '№ ' . $data->id;
        },
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'page_id',
        'content' => function($data){
            return $data->page->name;
        },
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'place',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'date',
        'content' => function($data){
            return date('H:i:s d.m.Y', strtotime($data->date) );
        },
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'status',
        'content' => function($data){
            return $data->getStatusDescription();
        },
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'name',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'contacts',
    ],
    [
        'class' => 'kartik\grid\ActionColumn',
        'dropdown' => false,
        'vAlign'=>'middle',
        'template' => '{view} {delete}',
        'urlCreator' => function($action, $model, $key, $index) { 
                return Url::to([$action,'id'=>$key]);
        },
        'viewOptions'=>['role'=>'modal-remote','title'=>'View','data-toggle'=>'tooltip'],
        'updateOptions'=>['role'=>'modal-remote','title'=>'Update', 'data-toggle'=>'tooltip'],
        'deleteOptions'=>['role'=>'modal-remote','title'=>'Delete', 
                          'data-confirm'=>false, 'data-method'=>false,// for overide yii data api
                          'data-request-method'=>'post',
                          'data-toggle'=>'tooltip',
                          'data-confirm-title'=>'Подтвердите действие',
                          'data-confirm-message'=>'Вы уверены что хотите удалить этого элемента?'], 
    ],

];   

views/applications/_contact_columns.php
<?php
use yii\helpers\Url;

return [
    [
        'class' => 'kartik\grid\SerialColumn',
        'width' => '30px',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'id',
        'content' => function($data){
            return '№ ' . $data->id;
        },
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'name',
        'content' => function($data){
            return $data->name;
        },
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'email',
    ],
    [
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'phone',
        'content' => function($data){
            return $data->phone;
        },
    ],
];   

views/applications/_contact_search.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

?>

<div class="client-form" style="padding: 20px;">

    <?php $form = ActiveForm::begin(); ?>
        <div class="row">
            <div class="col-md-4"> 
                <?= $form->field($model, 'search_name')->textInput([ 'value' => (isset($post['Contacts']['search_name'] ) ? $post['Contacts']['search_name'] : '') ]) ?>
            </div>

            <div class="col-md-4"> 
                <?= $form->field($model, 'search_email')->textInput([ 'value' => (isset($post['Contacts']['search_email']) ? $post['Contacts']['search_email']: '')  ]) ?>
            </div>

            <div class="col-md-3"> 
                <?= $form->field($model, 'search_phone')->textInput([ 'value' => (isset($post['Contacts']['search_phone']) ? $post['Contacts']['search_phone']: '')  ]) ?>
            </div>
            <div class="col-md-1">
                <div class="form-group" >
                    <?= Html::submitButton('Поиск' , ['style'=>'margin-top:25px;', 'class' =>  'btn btn-primary']) ?>
                </div>
            </div>
         </div>   
    <?php ActiveForm::end(); ?>
    
</div>

views/applications/_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Applications */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="applications-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'page_id')->textInput() ?>

    <?= $form->field($model, 'place')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'date')->textInput() ?>

    <?= $form->field($model, 'status')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'account_number')->textInput() ?>

    <?= $form->field($model, 'budget')->textInput() ?>

    <?= $form->field($model, 'pay')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'purpose_of_payment')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'pay_type')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'pay_date')->textInput() ?>

    <?= $form->field($model, 'utm')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'contacts')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'fields')->textarea(['rows' => 6]) ?>

  
	<?php if (!Yii::$app->request->isAjax){ ?>
	  	<div class="form-group">
	        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
	    </div>
	<?php } ?>

    <?php ActiveForm::end(); ?>
    
</div>

views/applications/_search.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

?>

<div class="client-form" style="padding: 20px;">

    <?php $form = ActiveForm::begin(); ?>
        <div class="row">
            <div class="col-md-4"> 
                <?= $form->field($model, 'search_name')->textInput([ 'value' => (isset($post['ApplicationsSearch']['search_name']) ? $post['ApplicationsSearch']['search_name'] : '' ) ]) ?>
            </div>

            <div class="col-md-3"> 
                <?= $form->field($model, 'search_page')->label()->widget(\kartik\select2\Select2::classname(), [
                    'data' => $model->getPageList(),
                    'options' => [
                        'placeholder' => 'Выберите',
                        'value' => (isset($post['ApplicationsSearch']['search_page']) ? $post['ApplicationsSearch']['search_page'] : '' ),
                    ],
                    'pluginOptions' => [
                        'allowClear' => true
                    ],
                ]); ?>
            </div>

            <div class="col-md-3"> 
                <?= $form->field($model, 'search_status')->label()->widget(\kartik\select2\Select2::classname(), [
                    'data' => $model->getStatusList(),
                    'options' => [
                        'placeholder' => 'Выберите',
                        'value' => (isset($post['ApplicationsSearch']['search_status']) ? $post['ApplicationsSearch']['search_status'] : '') ,
                    ],
                    'pluginOptions' => [
                        'allowClear' => true
                    ],
                ]); ?>
            </div>
            <div class="col-md-1">
                <?= Html::submitButton('Поиск' , ['style'=>'margin-top:25px;', 'class' =>  'btn btn-primary']) ?>
            </div>
            <div class="col-md-1">
                <?= Html::a('<i class="fa fa-bars fa-rotate-90"></i>', ['/applications/sorting',], [ 'title' => 'Настроить колонки таблицы', 'style'=>'margin-top:25px;', 'class' => 'btn btn-default', 'data-pjax'=>0, ]); ?>
            </div>
         </div>   
    <?php ActiveForm::end(); ?>
    
</div>

views/applications/index.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use kartik\grid\GridView;
use johnitvn\ajaxcrud\CrudAsset; 
use johnitvn\ajaxcrud\BulkButtonWidget;
use yii\widgets\Pjax;
use app\models\Applications;

$this->title = 'Заявки';
$this->params['breadcrumbs'][] = $this->title;
CrudAsset::register($this);

?>

        <div class="row">
            <div class="col-md-12">
                <ul class="nav nav-tabs">
                    <li class="active">
                        <a href="#default-tab-1" data-toggle="tab" aria-expanded="true">
                            <span class="visible-xs">Заявки</span>
                            <span class="hidden-xs">Заявки</span>
                        </a>
                    </li>
                    <li class="">
                        <a href="#default-tab-2" data-toggle="tab" aria-expanded="false">
                            <span class="visible-xs">Контакты</span>
                            <span class="hidden-xs">Контакты</span>
                        </a>
                    </li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane fade active in" id="default-tab-1">
                        <div class="row">
                            <?php Pjax::begin(['enablePushState' => false, 'id' => 'active-pjax']) ?>
                                <div class="col-md-12 col-sm-12">  
                                    <?= $this->render('_search', ['model' => $searchModel, 'post' => $post]); ?>
                                    <br>
                                    <?=GridView::widget([
                                        'id'=>'crud-datatable',
                                        'dataProvider' => $dataProvider,
                                        //'filterModel' => $searchModel,
                                        'pjax'=>true,
                                        'columns' => Applications::getColumns(),
                                        'toolbar'=> [
                                            [
                                                'content'=>'{export}'
                                            ],
                                        ],       
                                        'striped' => true,
                                        'condensed' => true,
                                        'responsive' => true,          
                                        'panel' => [
                                            'type' => 'primary', 
                                            'heading' => 'Список заявок',
                                            'before'=>'',
                                            'after'=>'',
                                        ]
                                    ])?>
                                </div>
                            <?php Pjax::end() ?>                        
                        </div>
                    </div>
                    <div class="tab-pane fade" id="default-tab-2">
                        <div class="row">
                            <?php Pjax::begin(['enablePushState' => false, 'id' => 'active-pjax']) ?>
                                <div class="col-md-12 col-sm-12">  
                                    <?= $this->render('_contact_search', ['model' => $contact, 'post' => $post]); ?>
                                    <br>
                                    <?=GridView::widget([
                                        'id'=>'crud-datatable',
                                        'dataProvider' => $contactProvider,
                                        //'filterModel' => $searchModel,
                                        'pjax'=>true,
                                        'columns' => require(__DIR__.'/_contact_columns.php'),
                                        'toolbar'=> [
                                            [
                                                'content'=>'{export}'
                                            ],
                                        ],       
                                        'striped' => true,
                                        'condensed' => true,
                                        'responsive' => true,          
                                        'panel' => [
                                            'type' => 'primary', 
                                            'heading' => 'Список контактов',
                                            'before'=>'',
                                            'after'=>'',
                                        ]
                                    ])?>
                                </div>
                            <?php Pjax::end() ?>                                     
                        </div>
                    </div>

                </div>

            </div>
        </div>

<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    "options" => [
        "tabindex" => false,
    ],
    "footer"=>"",// always need it for jquery plugin
])?>
<?php Modal::end(); ?>

views/applications/sorting.php
<?php
use kartik\sortinput\SortableInput;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>

<?php $form = ActiveForm::begin(); ?>
	<div class="panel panel-primary">

	    <div class="panel-heading">
			<h4 class="panel-title">Настройка столбцов</h4>
			<span class="pull-right"><?= Html::submitButton( 'Сохранить', ['class' => 'btn btn-xs btn-success']) ?>	</span>
		</div>

	    <div class="panel-body">
			<div class="row">
				<div class="col-sm-6">
					<label><h3 style="color:blue; font-weight:bold;"> Активно </h3></label>
					<?=SortableInput::widget([
					    'name'=>'active',
					    'items' => $active, 
					    'hideInput' => true,
					    'sortableOptions' => [
					        'connected'=>true,
					        'itemOptions'=>['class'=>'alert alert-success'],
					    ],
					    'options' => ['class'=>'form-control', 'readonly'=>true]
					])?>
				</div>

				<div class="col-sm-6">
					<label><h3 style="color:red; font-weight:bold;"> Неактивно </h3></label>
					<?=SortableInput::widget([
					    'name'=>'no-active',
					    'items' => $noactive, 
					    'hideInput' => true,
					    'sortableOptions' => [
					        'itemOptions'=>['class'=>'alert alert-warning'],
					        'connected'=>true,
					    ],
					    'options' => ['class'=>'form-control', 'readonly'=>true]
					])
					?>
				</div>
			</div>
		</div>
	</div>
<?php ActiveForm::end(); ?>

views/applications/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Applications */
?>
<div class="applications-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/applications/view.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>

<?php $form = ActiveForm::begin(); ?>
<div class="table-responsive">
    <table class="table table-bordered">
        <tbody>
        <tr>
            <td><b><?=$model->getAttributeLabel('date')?></b></td>
            <td><?= date('H:i:s d.m.Y', strtotime($model->date) )?></td>
        </tr>
        <tr>
            <td><b><?=$model->getAttributeLabel('name')?></b></td>
            <td><?=$model->name?></td>
        </tr>
        <tr>
            <td><b><?=$model->getAttributeLabel('page_id')?></b></td>
            <td><?=Html::encode($model->page->name)?></td>
        </tr>
        <tr>
            <td><b><?=$model->getAttributeLabel('place')?></b></td>
            <td><?= $model->place?></td>
        </tr>
        <tr>
            <td><b><?=$model->getAttributeLabel('account_number')?></b></td>
            <td><?= '№ ' . $model->account_number?></td>
        </tr>
        <tr>
            <td><b><?=$model->getAttributeLabel('status')?></b></td>
            <td>
                <?= $form->field($model, 'status')->label()->widget(\kartik\select2\Select2::classname(), [
                    'data' => $model->getStatusList(),
                    'options' => [
                        'onchange'=>'
                            $.post( "/applications/set-status?status='.'"+$(this).val()+"&id="+'.$model->id.', function( data ){
                            });' 
                    ],
                    'pluginOptions' => [
                        'allowClear' => true
                    ],
                ])->label(''); 
                ?>
            </td>
        </tr>
        <tr>
            <td><b><?=$model->getAttributeLabel('pay')?></b></td>
            <td><?= $model->getPayDescription()?></td>
        </tr>
        <tr>
            <td><b><?=$model->getAttributeLabel('pay_type')?></b></td>
            <td>
                <?php if($model->pay == 'not_payed') { ?>
                    <?= $form->field($model, 'pay_type')->label()->widget(\kartik\select2\Select2::classname(), [
                        'data' => $model->getPayTypeList(),
                        'options' => [
                            'placeholder' => 'Выберите тип оплаты',
                            'onchange'=>'
                                $.post( "/applications/set-pay-type?status='.'"+$(this).val()+"&id="+'.$model->id.', function( data ){
                                });' 
                        ],
                        'pluginOptions' => [
                            'allowClear' => true
                        ],
                    ])->label(''); 
                    ?>
                <?php } else { ?>
                    <?= $model->getPayTypeDescription()?>
                <?php } ?>
            </td>
        </tr>
        <tr>
            <td><b><?=$model->getAttributeLabel('budget')?></b></td>
            <td><?=Html::encode($model->budget)?></td>
        </tr>
        <tr>
            <td><b><?=$model->getAttributeLabel('purpose_of_payment')?></b></td>
            <td><?= $model->purpose_of_payment?></td>
        </tr>
        <tr>
            <td><b><?=$model->getAttributeLabel('pay_date')?></b></td>
            <td><?= $model->pay_date != null ? date('H:i:s d.m.Y', strtotime($model->pay_date) ) : '' ?></td>
        </tr>
        <tr>
            <td><b><?=$model->getAttributeLabel('utm')?></b></td>
            <td><?=$model->utm?></td>
        </tr>
        <tr>
            <td><b><?=$model->getAttributeLabel('contacts')?></b></td>
            <td><?=$model->contacts?></td>
        </tr>
        <tr>
            <td><b><?=$model->getAttributeLabel('fields')?></b></td>
            <td><?=$model->fields?></td>
        </tr>                                   
        </tbody>
    </table>
</div>
<?php ActiveForm::end(); ?>